// <auto-generated />
using System;
using DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DATA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222171514_QuestUpdate")]
    partial class QuestUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MODELS.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("MODELS.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MODELS.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MODELS.Entities.Campaign", b =>
                {
                    b.HasOne("MODELS.Entities.User", "User")
                        .WithMany("Campaigns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MODELS.Entities.CampaignState", "State", b1 =>
                        {
                            b1.Property<Guid>("CampaignId")
                                .HasColumnType("uniqueidentifier");

                            b1.PrimitiveCollection<string>("Achievements")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Chapter")
                                .HasColumnType("int");

                            b1.Property<bool>("Coral")
                                .HasColumnType("bit");

                            b1.Property<bool>("Crystal")
                                .HasColumnType("bit");

                            b1.Property<bool>("Dygorax")
                                .HasColumnType("bit");

                            b1.Property<bool>("Feather")
                                .HasColumnType("bit");

                            b1.Property<bool>("Felaxir")
                                .HasColumnType("bit");

                            b1.Property<bool>("Fire")
                                .HasColumnType("bit");

                            b1.Property<int>("ForgeLevel")
                                .HasColumnType("int");

                            b1.Property<int>("HerbalistLevel")
                                .HasColumnType("int");

                            b1.Property<bool>("Horn")
                                .HasColumnType("bit");

                            b1.Property<bool>("Hurom")
                                .HasColumnType("bit");

                            b1.Property<bool>("Hydar")
                                .HasColumnType("bit");

                            b1.Property<bool>("Ice")
                                .HasColumnType("bit");

                            b1.Property<bool>("Jekoros")
                                .HasColumnType("bit");

                            b1.Property<bool>("Kharia")
                                .HasColumnType("bit");

                            b1.Property<bool>("Korowon")
                                .HasColumnType("bit");

                            b1.Property<bool>("Mamuraak")
                                .HasColumnType("bit");

                            b1.Property<bool>("Metal")
                                .HasColumnType("bit");

                            b1.Property<bool>("Morkraas")
                                .HasColumnType("bit");

                            b1.Property<bool>("Nagarjas")
                                .HasColumnType("bit");

                            b1.Property<bool>("Orouxen")
                                .HasColumnType("bit");

                            b1.Property<bool>("Ozew")
                                .HasColumnType("bit");

                            b1.Property<bool>("Pazis")
                                .HasColumnType("bit");

                            b1.Property<bool>("Reikal")
                                .HasColumnType("bit");

                            b1.Property<bool>("Sirkaaj")
                                .HasColumnType("bit");

                            b1.Property<bool>("Taraska")
                                .HasColumnType("bit");

                            b1.Property<bool>("Tarragua")
                                .HasColumnType("bit");

                            b1.Property<bool>("Thunder")
                                .HasColumnType("bit");

                            b1.Property<bool>("Toramat")
                                .HasColumnType("bit");

                            b1.Property<bool>("Venom")
                                .HasColumnType("bit");

                            b1.Property<bool>("Vyraxen")
                                .HasColumnType("bit");

                            b1.Property<bool>("Xitheros")
                                .HasColumnType("bit");

                            b1.Property<bool>("Zekalith")
                                .HasColumnType("bit");

                            b1.Property<bool>("Zekath")
                                .HasColumnType("bit");

                            b1.HasKey("CampaignId");

                            b1.ToTable("Campaigns");

                            b1.WithOwner()
                                .HasForeignKey("CampaignId");

                            b1.OwnsMany("MODELS.Entities.Quest", "Quests", b2 =>
                                {
                                    b2.Property<Guid>("CampaignStateCampaignId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("QuestNumber")
                                        .HasColumnType("int");

                                    b2.Property<int>("Status")
                                        .HasColumnType("int");

                                    b2.HasKey("CampaignStateCampaignId", "Id");

                                    b2.ToTable("Quest");

                                    b2.WithOwner()
                                        .HasForeignKey("CampaignStateCampaignId");
                                });

                            b1.Navigation("Quests");
                        });

                    b.Navigation("State")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MODELS.Entities.Player", b =>
                {
                    b.HasOne("MODELS.Entities.Campaign", "Campaign")
                        .WithMany("Players")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MODELS.Entities.PlayerResources", "Resources", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Albalacea")
                                .HasColumnType("int");

                            b1.Property<int>("Anthemon")
                                .HasColumnType("int");

                            b1.Property<int>("Blood")
                                .HasColumnType("int");

                            b1.Property<int>("Bones")
                                .HasColumnType("int");

                            b1.Property<int>("Coral")
                                .HasColumnType("int");

                            b1.Property<int>("Crystal")
                                .HasColumnType("int");

                            b1.Property<int>("Feather")
                                .HasColumnType("int");

                            b1.Property<int>("Fire")
                                .HasColumnType("int");

                            b1.Property<int>("Horn")
                                .HasColumnType("int");

                            b1.Property<int>("Ice")
                                .HasColumnType("int");

                            b1.Property<int>("Iride")
                                .HasColumnType("int");

                            b1.Property<int>("Kobaureo")
                                .HasColumnType("int");

                            b1.Property<int>("Mellis")
                                .HasColumnType("int");

                            b1.Property<int>("Metal")
                                .HasColumnType("int");

                            b1.Property<int>("Nillea")
                                .HasColumnType("int");

                            b1.Property<int>("Saelicornia")
                                .HasColumnType("int");

                            b1.Property<int>("Scales")
                                .HasColumnType("int");

                            b1.Property<int>("Tarmaret")
                                .HasColumnType("int");

                            b1.Property<int>("Thunder")
                                .HasColumnType("int");

                            b1.Property<int>("Venom")
                                .HasColumnType("int");

                            b1.Property<int>("Zima")
                                .HasColumnType("int");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.OwnsMany("MODELS.Entities.PlayerSkill", "Skills", b1 =>
                        {
                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Level")
                                .HasColumnType("int");

                            b1.Property<int>("Skill")
                                .HasColumnType("int");

                            b1.HasKey("PlayerId", "Id");

                            b1.ToTable("PlayerSkill");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Campaign");

                    b.Navigation("Resources")
                        .IsRequired();

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("MODELS.Entities.Campaign", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("MODELS.Entities.User", b =>
                {
                    b.Navigation("Campaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
